"""Fast H3 clip lengths, continuation limits, and aspect ratios."""

MAX_MEDIA_SECONDS = 3600

MAX_CLIP_FRAMES = 1440

FRAME_RATE = 24

MIN_CLIP_COUNT = 2

MAX_CLIP_COUNT = 8

MAX_PROMPT_CHARACTERS = 800

MIN_CLIP_SECONDS = 5.167

MAX_CLIP_SECONDS = 14.375

MAX_QUEUED_CLIPS = 2

DEFAULT_CLIP_SECONDS = 6.0

STEP_CLIP_SECONDS = 0.001

OPTIONS_ASPECT = ["16:9", "1:1", "9:16", "4:3"]

DEFAULT_ASPECT = "16:9"

DEFAULT_CLIP_COUNT = 3

__all__ = [
    "DEFAULT_ASPECT",
    "DEFAULT_CLIP_COUNT",
    "DEFAULT_CLIP_SECONDS",
    "FRAME_RATE",
    "MAX_CLIP_COUNT",
    "MAX_CLIP_FRAMES",
    "MAX_CLIP_SECONDS",
    "MAX_MEDIA_SECONDS",
    "MAX_PROMPT_CHARACTERS",
    "MAX_QUEUED_CLIPS",
    "MIN_CLIP_COUNT",
    "MIN_CLIP_SECONDS",
    "OPTIONS_ASPECT",
    "STEP_CLIP_SECONDS",
]
