"""Generation session timing and startup limits."""

MAX_SESSION_CAPACITY = 4

MAX_MESSAGE_TYPES = 16

MIN_CAPTURE_SECONDS = 0.1

MAX_PROMPT_CHARACTERS = 20_000

DEFAULT_SESSION_CAPACITY = 1

__all__ = [
    "DEFAULT_SESSION_CAPACITY",
    "MAX_MESSAGE_TYPES",
    "MAX_PROMPT_CHARACTERS",
    "MAX_SESSION_CAPACITY",
    "MIN_CAPTURE_SECONDS",
]
