"""Static generation session values used by the connector."""

MAX_SESSION_CAPACITY = 4

MAX_MESSAGE_TYPES = 16

MIN_CAPTURE_SECONDS = 0.1

MAX_PROMPT_CHARACTERS = 20_000

MAX_PROJECT_FILE_BYTES = 65_536

MAX_VERSION_CHARACTERS = 80

DEFAULT_SESSION_CAPACITY = 1

PACKAGE_IDENTITY_PATTERN = "[a-f0-9]{64}"
