"""Generation session timing and startup limits."""

MAX_SESSION_CAPACITY = 4

MAX_MESSAGE_TYPES = 16

MIN_CAPTURE_SECONDS = 0.1

MAX_PROMPT_CHARACTERS = 20_000

DEFAULT_SESSION_CAPACITY = 1

CANCELLATION_POLL_SECONDS = 0.1

CAPTURE_DRAIN_SECONDS = 0.5

__all__ = [
    "CANCELLATION_POLL_SECONDS",
    "CAPTURE_DRAIN_SECONDS",
    "DEFAULT_SESSION_CAPACITY",
    "MAX_MESSAGE_TYPES",
    "MAX_PROMPT_CHARACTERS",
    "MAX_SESSION_CAPACITY",
    "MIN_CAPTURE_SECONDS",
]
