"""Speech pace and transcript limits."""

MIN_SPEECH_SECONDS = 4

MAX_SCENE_CHARACTERS = 800

MAX_SCRIPT_CHARACTERS = 10_000

MAX_WORDS_PER_MINUTE = 1000

RECORDING_TAIL_SECONDS = 20

DEFAULT_SCRIPT = "Hello. Welcome to this short video."

DEFAULT_WORDS_PER_MINUTE = 140

__all__ = [
    "DEFAULT_SCRIPT",
    "DEFAULT_WORDS_PER_MINUTE",
    "MAX_SCENE_CHARACTERS",
    "MAX_SCRIPT_CHARACTERS",
    "MAX_WORDS_PER_MINUTE",
    "MIN_SPEECH_SECONDS",
    "RECORDING_TAIL_SECONDS",
]
