globs:
    - '**/*.md'
config:
    MD007:
        indent: 4
    MD013: false
    MD060: false
ignores:
    - '.git/**'
    - '.artifacts/**'
    - '.venv/**'
    - 'node_modules/**'
    - 'web/dist/**'
    - 'rules/DOCUMENTATION.md'
