rules:
    - id: reactor-torch-no-jit-script
      message: Do not compile Torch scripts in the connector.
      severity: ERROR
      languages:
          - python
      pattern: torch.jit.script(...)
    - id: reactor-torch-no-load
      message: Do not deserialize model files with torch.load in the connector.
      severity: ERROR
      languages:
          - python
      pattern-either:
          - pattern: torch.load(...)
          - pattern: from torch import load
    - id: reactor-torch-no-lstm-cell
      message: Do not call torch.lstm_cell in the connector.
      severity: ERROR
      languages:
          - python
      pattern-either:
          - pattern: torch.lstm_cell(...)
          - pattern: from torch import lstm_cell
    - id: reactor-python-no-diskcache-direct-use
      message: Do not import or use DiskCache in the connector.
      severity: ERROR
      languages:
          - python
      pattern-either:
          - pattern: import diskcache
          - pattern: from diskcache import $NAME
          - pattern: diskcache.Cache(...)
