import io as bytes_io
from fractions import Fraction
from typing import Protocol

import numpy as np
from numpy.typing import NDArray

from . import io as io

class ComfyExtension:
    async def on_load(self) -> None: ...
    async def get_node_list(self) -> list[type[io.ComfyNode]]: ...

class Input:
    class Video(Protocol):
        def get_stream_source(self) -> str | bytes_io.BytesIO: ...
        def get_active_trim_window(self) -> tuple[float, float]: ...
        def get_bit_depth(self) -> int: ...
        def get_color_space(self) -> str: ...

    class Image(Protocol):
        @property
        def ndim(self) -> int: ...
        @property
        def shape(self) -> tuple[int, ...]: ...
        def detach(self) -> Input.Image: ...
        def cpu(self) -> Input.Image: ...
        def numpy(self) -> NDArray[np.float32]: ...
        def __getitem__(self, index: int) -> Input.Image: ...

class VideoComponents(Protocol):
    images: Input.Image
    frame_rate: Fraction

class InputImpl:
    class VideoFromFile(Input.Video):
        def __init__(self, file: str) -> None: ...

    class VideoFromComponents(Input.Video):
        def get_components(self) -> VideoComponents: ...
