"""Audio sample rate and channel limits."""

AUDIO_ENCODE_BLOCK_SAMPLES = 1024

AUDIO_WRITE_BLOCK_SAMPLES = 4096

PCM_SAMPLE_BYTES = 2

SAMPLE_RATE = 48_000

MIN_CHANNELS = 1

MAX_CHANNELS = 2

__all__ = [
    "AUDIO_ENCODE_BLOCK_SAMPLES",
    "AUDIO_WRITE_BLOCK_SAMPLES",
    "MAX_CHANNELS",
    "MIN_CHANNELS",
    "PCM_SAMPLE_BYTES",
    "SAMPLE_RATE",
]
