"""Video input dimensions, formats, and frame limits."""

SOURCE_COPY_CHUNK_BYTES = 65_536

# ITU-T H.273 transfer-characteristic codes for PQ and HLG HDR video.
HDR_TRANSFER_CODES = (16, 18)

MAX_FRAME_RATE = 120

DEFAULT_FRAME_RATE = 24

COMPONENT_BITS = 8

MIN_FRAME_DIMENSION = 2

MAX_FRAME_DIMENSION = 4096

MIN_SOURCE_FRAMES = 33

MAX_COMPONENT_BITS = 8

MAX_START_SECONDS = 3600

ENCODER_NAME = "libx264"

ENCODER_PIXEL_FORMAT = "yuv420p"

ENCODER_PRESET = "veryfast"

ENCODER_CRF = "18"

__all__ = [
    "COMPONENT_BITS",
    "DEFAULT_FRAME_RATE",
    "ENCODER_CRF",
    "ENCODER_NAME",
    "ENCODER_PIXEL_FORMAT",
    "ENCODER_PRESET",
    "HDR_TRANSFER_CODES",
    "MAX_COMPONENT_BITS",
    "MAX_FRAME_DIMENSION",
    "MAX_FRAME_RATE",
    "MAX_START_SECONDS",
    "MIN_FRAME_DIMENSION",
    "MIN_SOURCE_FRAMES",
    "SOURCE_COPY_CHUNK_BYTES",
]
