"""Webcam frame dimensions and upload limits."""

MAX_CAMERA_JPEG_BYTES = 300_000

MAX_CAMERA_WIDTH = 640

MAX_CAMERA_HEIGHT = 480

CAMERA_FRAME_RATE = 24

CAMERA_READY_SECONDS = 2

CAMERA_TIMEOUT_SECONDS = 3
