"""Webcam frame dimensions and upload limits."""

MAX_CAMERA_JPEG_BYTES = 300_000

MAX_CAMERA_WIDTH = 640

MAX_CAMERA_HEIGHT = 480

CAMERA_FRAME_RATE = 24

CAMERA_READY_SECONDS = 2

CAMERA_TIMEOUT_SECONDS = 3

__all__ = [
    "CAMERA_FRAME_RATE",
    "CAMERA_READY_SECONDS",
    "CAMERA_TIMEOUT_SECONDS",
    "MAX_CAMERA_HEIGHT",
    "MAX_CAMERA_JPEG_BYTES",
    "MAX_CAMERA_WIDTH",
]
