"""Generation session timing and startup limits."""

MAX_SESSION_RECORD_BYTES = 1024

MAX_SESSION_RECORD_DEPTH = 2

MAX_MESSAGE_TYPES = 16

MIN_CAPTURE_SECONDS = 0.1

MAX_PROMPT_CHARACTERS = 20_000

DEFAULT_SESSION_CAPACITY = 1

CANCELLATION_POLL_SECONDS = 0.1

CAPTURE_DRAIN_SECONDS = 0.5
