"""Speech pace and transcript limits."""

MIN_SPEECH_SECONDS = 4

MAX_SCENE_CHARACTERS = 800

MAX_SCRIPT_CHARACTERS = 10_000

MAX_WORDS_PER_MINUTE = 1000

MIN_WORDS_PER_MINUTE = 1

RECORDING_TAIL_SECONDS = 20

DEFAULT_SCRIPT = "Hello. Welcome to this short video."

DEFAULT_WORDS_PER_MINUTE = 140
