"""Image dimensions, color channels, and upload limits."""

BATCH_IMAGE_DIMENSIONS = 4

RGB_CHANNELS = 3

MAX_IMAGE_DIMENSION = 8192

RGB_ARRAY_DIMENSIONS = 3

MAX_FRAME_DIMENSION = 8192

__all__ = [
    "BATCH_IMAGE_DIMENSIONS",
    "MAX_FRAME_DIMENSION",
    "MAX_IMAGE_DIMENSION",
    "RGB_ARRAY_DIMENSIONS",
    "RGB_CHANNELS",
]
