"""Video input dimensions, formats, and frame limits."""

MAX_FRAME_RATE = 120

DEFAULT_FRAME_RATE = 24

BROWSER_RECORDING_FRAME_RATE = 30

COMPONENT_BITS = 8

MIN_FRAME_DIMENSION = 2

MAX_FRAME_DIMENSION = 4096

MIN_SOURCE_FRAMES = 33

MAX_COMPONENT_BITS = 8

MAX_START_SECONDS = 3600

ENCODER_NAME = "libx264"

ENCODER_PIXEL_FORMAT = "yuv420p"

ENCODER_PRESET = "veryfast"

ENCODER_CRF = "18"

__all__ = [
    "BROWSER_RECORDING_FRAME_RATE",
    "COMPONENT_BITS",
    "DEFAULT_FRAME_RATE",
    "ENCODER_CRF",
    "ENCODER_NAME",
    "ENCODER_PIXEL_FORMAT",
    "ENCODER_PRESET",
    "MAX_COMPONENT_BITS",
    "MAX_FRAME_DIMENSION",
    "MAX_FRAME_RATE",
    "MAX_START_SECONDS",
    "MIN_FRAME_DIMENSION",
    "MIN_SOURCE_FRAMES",
]
