"""Static media workers values used by the connector."""

MAX_REPORT_BYTES = 4096

METADATA_TIMEOUT_SECONDS = 10

RECORDING_TIMEOUT_SECONDS = 60

INPUT_TIMEOUT_SECONDS = 60

SHUTDOWN_TIMEOUT_SECONDS = 2
