"""Media worker timeouts and response limits."""

MAX_REPORT_BYTES = 4096

METADATA_TIMEOUT_SECONDS = 10

RECORDING_TIMEOUT_SECONDS = 60

INPUT_TIMEOUT_SECONDS = 60

SHUTDOWN_TIMEOUT_SECONDS = 2

__all__ = [
    "INPUT_TIMEOUT_SECONDS",
    "MAX_REPORT_BYTES",
    "METADATA_TIMEOUT_SECONDS",
    "RECORDING_TIMEOUT_SECONDS",
    "SHUTDOWN_TIMEOUT_SECONDS",
]
