"""Live-session lifetimes, input queues, and message limits."""

MAX_QUEUED_MOVEMENT_SECONDS = 2

CAPABILITY_BYTES = 32

CAPABILITY_CHARACTERS = (CAPABILITY_BYTES * 4 + 2) // 3

LEASE_BYTES = 16

CLIENT_TIMEOUT_SECONDS = 5

STALE_INPUT_SECONDS = 0.75

MAX_PENDING_INPUTS = 8

MAX_PREVIEW_CHARACTERS = 350_000

CLOSED_SESSION_RETENTION_SECONDS = 30

MAX_STORED_SESSIONS = 32

MAX_SEQUENCE = 2**53 - 1

MAX_SEQUENCE_DIGITS = 16

MIN_QUEUE_ITEM_FIELDS = 4

MAX_CLIENT_ID_CHARACTERS = 128

MAX_QUEUED_MOVEMENTS = 8

COMMAND_TIMEOUT_SECONDS = 5

UPLOAD_TIMEOUT_SECONDS = 2

MAX_ACTION_BYTES = 90_000

CAMERA_UPLOAD_CHUNK_BYTES = 16_384

INPUT_POLL_SECONDS = 0.05

CAMERA_INVITATION_TIMEOUT_SECONDS = 5

CONTROL_INVITATION_TIMEOUT_SECONDS = 60

PREVIEW_INTERVAL_SECONDS = 0.1

MAX_PREVIEW_WIDTH = 640

MAX_PREVIEW_HEIGHT = 360

PREVIEW_JPEG_QUALITY = 75
