"""Static live values used by the connector."""

MAX_QUEUED_MOVEMENT_SECONDS = 2

CAPABILITY_CHARACTERS = 43

CLIENT_TIMEOUT_SECONDS = 5

STALE_INPUT_SECONDS = 0.75

MAX_PENDING_INPUTS = 8

MAX_PREVIEW_CHARACTERS = 350_000

CLOSED_SESSION_RETENTION_SECONDS = 30

MAX_STORED_SESSIONS = 32

MAX_SEQUENCE_DIGITS = 15

MIN_QUEUE_ITEM_FIELDS = 4

MAX_CLIENT_ID_CHARACTERS = 128

MAX_QUEUED_MOVEMENTS = 8

COMMAND_TIMEOUT_SECONDS = 5

UPLOAD_TIMEOUT_SECONDS = 2
