"""Static node defaults and choices."""

DEFAULT_DURATION_SECONDS = 5.0

MIN_DURATION_SECONDS = 0.1

MAX_DURATION_SECONDS = 60.0

STEP_DURATION_SECONDS = 0.1

DEFAULT_SEED = 42

MAX_SEED = 2**32 - 1

MAX_VARIATION = 2**31 - 1


DEFAULT_POINTER_POSITION = 0.5

STEP_POINTER_POSITION = 0.01

DEFAULT_WEBCAM_SECONDS = 10

MIN_WEBCAM_SECONDS = 0.1

MAX_WEBCAM_SECONDS = 60

STEP_WEBCAM_SECONDS = 0.1

__all__ = [
    "DEFAULT_DURATION_SECONDS",
    "DEFAULT_POINTER_POSITION",
    "DEFAULT_SEED",
    "DEFAULT_WEBCAM_SECONDS",
    "MAX_DURATION_SECONDS",
    "MAX_SEED",
    "MAX_VARIATION",
    "MAX_WEBCAM_SECONDS",
    "MIN_DURATION_SECONDS",
    "MIN_WEBCAM_SECONDS",
    "STEP_DURATION_SECONDS",
    "STEP_POINTER_POSITION",
    "STEP_WEBCAM_SECONDS",
]
