"""Package version and manifest limits."""

MAX_PROJECT_FILE_BYTES = 65_536
MAX_VERSION_CHARACTERS = 80
PACKAGE_IDENTITY_PATTERN = "[a-f0-9]{64}"
MAX_MANIFEST_BYTES = 1_048_576
MAX_MANIFEST_DEPTH = 4

__all__ = [
    "MAX_MANIFEST_BYTES",
    "MAX_MANIFEST_DEPTH",
    "MAX_PROJECT_FILE_BYTES",
    "MAX_VERSION_CHARACTERS",
    "PACKAGE_IDENTITY_PATTERN",
]
