"""Static settings values used by the connector."""

MAX_TIMEOUT_SECONDS = 3600

DEFAULT_MAX_CAPTURE_SECONDS = 60

DEFAULT_MAX_SESSION_SECONDS = 180

DEFAULT_CONNECT_TIMEOUT_SECONDS = 60

DEFAULT_FRAME_TIMEOUT_SECONDS = 30

DEFAULT_CLEANUP_TIMEOUT_SECONDS = 10

DEFAULT_QUEUE_TIMEOUT_SECONDS = 120

DEFAULT_MAX_UPLOAD_MEGABYTES = 100

DEFAULT_MAX_CAPTURE_MEGABYTES = 512

DEFAULT_MAX_QUEUE_MEGABYTES = 64

DEFAULT_DISCOVERY_INTERVAL_HOURS = 24

DEFAULT_DISCOVERY_AUTO_CHECK = True

MAX_SETTINGS_BYTES = 4096

MAX_SETTINGS_FILE_BYTES = 65_536

SETTINGS_TIMEOUT_SECONDS = 5
