"""Describe editable examples alongside their implemented model operations."""

from .live_examples import live_examples
from .workflow_example import Example

BASE_EXAMPLES = (
    Example(
        "lingbot-02-live-camera",
        "LingBot: Move through an image",
        "ReactorIncLingBotExplore",
        "lingbot",
        "A path through a quiet forest.",
        image=True,
        controls=("idle", "idle", "idle", 5.0, True),
        duration_seconds=10.0,
        interactive=True,
    ),
    Example(
        "lingbot-world-2-02-live-camera",
        "LingBot World 2: Move and look independently",
        "ReactorIncLingBotWorld2Explore",
        "lingbot-world-2",
        "A path through a quiet forest.",
        image=True,
        controls=("idle", "idle", "idle", "idle", 5.0, True),
        duration_seconds=10.0,
        interactive=True,
    ),
    Example(
        "fast-h3-03-first-and-last-frames",
        "Fast H3: Connect two images with motion",
        "ReactorIncFastGenerate",
        "fast-h3",
        "Move smoothly from the first scene to the final scene. "
        "Keep the motion natural. Soft ambience.",
        controls=("16:9",),
        image=True,
        ending_image=True,
        audio=True,
        duration_seconds=6.0,
    ),
    Example(
        "fast-h3-04-ending-frame",
        "Fast H3: Finish on a chosen image",
        "ReactorIncFastGenerate",
        "fast-h3",
        "The camera moves slowly toward this final view. Keep the movement smooth. Soft ambience.",
        controls=("16:9",),
        ending_image=True,
        audio=True,
        duration_seconds=6.0,
    ),
    Example(
        "fast-h3-01-text-to-video",
        "Fast H3: Build a clip with sound",
        "ReactorIncFastGenerate",
        "fast-h3",
        "A small stream flows over smooth stones. Water splashes softly and birds call.",
        controls=("16:9",),
        audio=True,
        duration_seconds=6.0,
    ),
    Example(
        "fast-h3-02-image-to-video",
        "Fast H3: Animate a starting image",
        "ReactorIncFastGenerate",
        "fast-h3",
        "Bring this scene to life with gentle motion. Keep the subject and composition. "
        "Soft natural ambience.",
        controls=("16:9",),
        image=True,
        audio=True,
        duration_seconds=6.0,
    ),
    Example(
        "ltx2-01-speaking-portrait",
        "LTX: Make a portrait speak",
        "ReactorIncLtxSpeak",
        "ltx2",
        "A person faces the camera and speaks calmly.",
        controls=("Hello. Welcome to this short video.", 140),
        image=True,
        audio=True,
    ),
    Example(
        "visko-stable-01-text-to-video",
        "Visko Stable: Video with sound",
        "ReactorIncViskoStableGenerate",
        "visko-orbis-stable",
        "A small stream flows over smooth stones in a quiet forest.",
        controls=(
            "Water splashes softly over stones, with birds calling in the distance.",
            "",
            True,
            False,
        ),
        audio=True,
    ),
    Example(
        "visko-stable-02-image-to-video",
        "Visko Stable: Animate an image with sound",
        "ReactorIncViskoStableGenerate",
        "visko-orbis-stable",
        "The camera moves slowly along a forest path. Ferns and leaves sway gently. "
        "Keep the trees, path, and lighting from the starting image.",
        controls=("", "", True, True),
        image=True,
        audio=True,
    ),
    Example(
        "visko-dynamic-01-text-to-video",
        "Visko Dynamic: Video with sound",
        "ReactorIncViskoDynamicGenerate",
        "visko-orbis-dynamic",
        "A small stream flows over smooth stones in a quiet forest.",
        controls=(
            "Water splashes softly over stones, with birds calling in the distance.",
            "",
            True,
            False,
        ),
        audio=True,
    ),
    Example(
        "visko-dynamic-02-image-to-video",
        "Visko Dynamic: Animate an image with sound",
        "ReactorIncViskoDynamicGenerate",
        "visko-orbis-dynamic",
        "The camera moves slowly along a forest path. Ferns and leaves sway gently. "
        "Keep the trees, path, and lighting from the starting image.",
        controls=("", "", True, True),
        image=True,
        audio=True,
    ),
    Example(
        "x2-01-edit-video",
        "X2: Edit a local video",
        "ReactorIncX2EditVideo",
        "x2",
        "Change the scene to a soft watercolor painting. Keep the movement and composition.",
        controls=(False, False, 0.5, 0.5),
        video=True,
        seed=False,
    ),
    Example(
        "x2-02-reference-edit",
        "X2: Edit with a reference image",
        "ReactorIncX2EditVideo",
        "x2",
        "Replace the main subject with the subject from the reference image. Keep the background.",
        controls=(False, False, 0.5, 0.5),
        video=True,
        seed=False,
        reference=True,
    ),
    Example(
        "sana-streaming-01-edit-video",
        "SANA: Edit a local video",
        "ReactorIncSanaEditVideo",
        "sana-streaming",
        "Change the scene to a soft watercolor painting. Keep the movement and composition.",
        controls=(0,),
        video=True,
    ),
    Example(
        "helios-01-text-to-video",
        "Helios: Text to video",
        "ReactorIncHeliosGenerate",
        "helios",
        "A red ball rolls slowly across a wooden table. The camera stays still.",
    ),
    Example(
        "helios-02-image-to-video",
        "Helios: Animate a local image",
        "ReactorIncHeliosAnimate",
        "helios",
        "The scene comes to life with gentle motion. Keep the subject and composition.",
        image=True,
    ),
    Example(
        "lingbot-01-explore-image",
        "LingBot: Explore a local image",
        "ReactorIncLingBotExplore",
        "lingbot",
        "A quiet garden path. Move forward slowly through the scene.",
        image=True,
        controls=("forward", "idle", "idle", 5.0, False),
    ),
    Example(
        "lingbot-world-2-01-explore-image",
        "LingBot World 2: Explore a local image",
        "ReactorIncLingBotWorld2Explore",
        "lingbot-world-2",
        "A quiet garden path. Move forward slowly through the scene.",
        image=True,
        controls=("forward", "idle", "idle", "idle", 5.0, False),
    ),
    Example(
        "longlive-v2-01-text-to-video",
        "LongLive: Opening shot",
        "ReactorIncLongLiveGenerate",
        "longlive-v2",
        "A fox walks along a forest path. The camera follows slowly.",
    ),
    Example(
        "longlive-v2-02-storyboard",
        "LongLive: Soft transition and hard cut",
        "ReactorIncLongLiveStoryboard",
        "longlive-v2",
        "A fox walks along a forest path. The camera follows slowly.",
        storyboard=True,
    ),
)


SEQUENCE_EXAMPLES = tuple(
    Example(
        f"helios-{'04-image-sequence' if image else '03-prompt-sequence'}",
        "Helios: Animate an image through prompt changes"
        if image
        else "Helios: Follow a prompt sequence",
        "ReactorIncHeliosSequence",
        "helios",
        "The camera moves slowly along a forest path in soft morning light.",
        image=image,
        prompt_sequence=True,
        duration_seconds=8,
    )
    for image in (False, True)
)

EXAMPLES = (*BASE_EXAMPLES, *live_examples(BASE_EXAMPLES), *SEQUENCE_EXAMPLES)
